config/routes.rb
Blog::Application.routes.draw do

  devise_for :users

  resources :recipes do
    resources :reviews #nested route
  end

  get "emailrecipe/:id(.:format)" => 'recipes#email_recipe', :as => 'email_recipe' 
  get "store" => "stores#index", :as => 'store' 
  get "stores/:id(.:format)" => "stores#show", :as => 'store_id' 

  get "page/home"
  get "page/about_us"
  get "page/recipes"
  get "page/product"
  get "page/articles"
  get "page/calender"
  get "page/blog"
  get "page/login"
  
  get "say/hello"
  get "say/goodbye"

    root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :cost, :image, :ingredients, :last_made, :made_by, :name, :serves, :avatar
  validates_presence_of :name, :ingredients, :made_by
  validates_numericality_of :serves, :only_integer => true
  validates_uniqueness_of :name
  
  has_many :reviews, :dependent => :destroy
  has_attached_file :avatar
  # , :styles => { :original => "300x300>", :thumb => "100x100>" }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :recipe
  attr_accessible :author, :content, :rating, :title
end

app/models/store.rb
class Store < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def about_us
  end

  def recipes
  end

  def product
  end

  def articles
  end

  def calender
    @my_time = Time.now
    @name = "Pawan"
    @products = %w(Skiis Boots Poles Mittens Mask hat)
    
  end

  def blog
  end

  def login
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  # before_filter :authenticate
  before_filter :authenticate_user!

def email_recipe
  # User.find_by_newsletter(:true).each
  RecipeMailer.send_recipe( params[:id], if current_user.try(:admin) then current_user end ).deliver
  
  redirect_to recipes_url
end



  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
      format.xml { render xml: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
      format.xml { render xml: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
  
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username =="foo" && password =="bar"
    end
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # POST /reviews
  # POST /reviews.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.create(params[:review])

    redirect_to recipe_path(@recipe)

  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.find(params[:id])
    @review.destroy

    redirect_to recipe_path(@recipe)
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    
  end
  def goodbye
     
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @recipes = Recipe.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
      format.xml { render xml: @recipes }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
      format.xml { render xml: @recipe }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def calender(number)
     return number*2
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Pawan's Recipes</title>
  
  <%= stylesheet_link_tag    "application", :media => "screen" %>
  <%= stylesheet_link_tag    "print", :media => "print" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

<div id="wrapper"><!-- #wrapper -->

	<nav><!-- top nav -->
<%= render :partial => 'shared/navigation' %>
	</nav><!-- end of top nav -->
	
	<header><!-- header -->
		<div id="headerlogo"><%= image_tag "kookycook.png", :alt => "Pawan's Picture" %></div>
		<h1><%= link_to "Pawan's Recipes", page_home_path %></h1>
		<h2>Isn't he cute?</h2>
	</header><!-- end of header -->
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- content -->
				<div style="">
					<% if flash[:notice] %>
					<p class="notice"><%= flash[:notice].html_safe %></p>
					<% end %>
					<% if flash[:alert] %>
       				<p class="alert"><%= flash[:alert].html_safe %></p>
       				<% end %>
				</div>
			      
			      <h2>Welcome <%= if current_user.try(:admin) then current_user.name end %></h2> 
			
<%= yield %>


			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Links</h3>
					<ul>
		<li><%= link_to_unless_current "Recipes", recipes_path %></li>
		<li><%= link_to_unless_current "Store", store_path %></li>						
<!--
						
												<li><a href="#">Swap Recipes</a></li>
												<li><a href="#">Play Games</a></li>
												<li><a href="#">Buy Stuff</a></li>
												<li><a href="#">Trade Stuff</a></li>-->
						
					</ul>
					
				<h3>Sponsors</h3>
					<%= image_tag "ad125.jpg" %> <br /><%= image_tag "ad125.jpg" %><br /><br />

				<!--
				<h3>Connect With Us</h3>
									<ul>
										<li><a href="#">Twitter</a></li>
										<li><a href="#">Facebook</a></li>
									</ul>-->
				

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Links</h4>
								<ul>
		<li><%= link_to_unless_current "Recipes", recipes_path %></li>
		<li><%= link_to_unless_current "Store", store_path %></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<!--
					<aside class="footer-segment">
												<h4>Awesome Stuff</h4>
													<ul>
														<li><a href="#">one linkylink</a></li>
														<li><a href="#">two linkylinks</a></li>
														<li><a href="#">three linkylinks</a></li>
													</ul>
										</aside><!-- end of #second footer segment ->
					
										<aside class="footer-segment">
												<h4>Coolness</h4>
													<ul>
														<li><a href="#">one linkylink</a></li>
														<li><a href="#">two linkylinks</a></li>
														<li><a href="#">three linkylinks</a></li>
													</ul>
										</aside><!-- end of #third footer segment ->-->
					
					
					<aside class="footer-segment">
							<h4>Recipe</h4>
								<p>&copy; 2013 <%= link_to "Home", page_home_path %></p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->


</body>
</html>

app/views/layouts/recipes.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Pawan's Recipes</title>
  
  <%= stylesheet_link_tag    "application", :media => "screen" %>
  <%= stylesheet_link_tag    "print", :media => "print" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

<div id="wrapper"><!-- #wrapper -->

	<nav><!-- top nav -->
<%= render :partial => 'shared/navigation' %>
	</nav><!-- end of top nav -->
	
	<header><!-- header -->
		<div id="headerlogo"><%= image_tag "kookycook.png", :alt => "Pawan's Picture" %></div>
		<h1><%= link_to "Pawan's Recipes", page_home_path %></h1>
		<h2>Isn't he cute?</h2>
	</header><!-- end of header -->
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- content -->
			
			
<%= yield %>


			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Links</h3>
					<ul>
						<li><%= link_to_unless_current "Recipes", recipes_path %></li>
		<li><%= link_to_unless_current "Store", store_path %></li>						
<!--
						
												<li><a href="#">Swap Recipes</a></li>
												<li><a href="#">Play Games</a></li>
												<li><a href="#">Buy Stuff</a></li>
												<li><a href="#">Trade Stuff</a></li>-->
						
					</ul>
					
				<h3>Sponsors</h3>
					<%= image_tag "ad125.jpg" %> <br /><%= image_tag "ad125.jpg" %><br /><br />

				<!--
				<h3>Connect With Us</h3>
									<ul>
										<li><a href="#">Twitter</a></li>
										<li><a href="#">Facebook</a></li>
									</ul>-->
				

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Links</h4>
								<ul>
		<li><%= link_to_unless_current "Recipes", recipes_path %></li>
		<li><%= link_to_unless_current "Store", store_path %></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<!--
					<aside class="footer-segment">
												<h4>Awesome Stuff</h4>
													<ul>
														<li><a href="#">one linkylink</a></li>
														<li><a href="#">two linkylinks</a></li>
														<li><a href="#">three linkylinks</a></li>
													</ul>
										</aside><!-- end of #second footer segment ->
					
										<aside class="footer-segment">
												<h4>Coolness</h4>
													<ul>
														<li><a href="#">one linkylink</a></li>
														<li><a href="#">two linkylinks</a></li>
														<li><a href="#">three linkylinks</a></li>
													</ul>
										</aside><!-- end of #third footer segment ->-->
					
					
					<aside class="footer-segment">
							<h4>Recipe</h4>
								<p>&copy; 2013 <%= link_to "Home", page_home_path %></p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->


</body>
</html>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/articles.html.erb
<h1>Page#articles</h1>
<p>Find me in app/views/page/articles.html.erb</p>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calender.html.erb
<h1>Page#calender</h1>
<p>Find me in app/views/page/calender.html.erb</p>

<%= @name + @my_time.to_s %>
<ol>
	<% @products.each do |product| %>
	<li><%= product.capitalize %></li>
	<% end %>	
</ol>
Helper Example <%= calender(2) %>

app/views/page/home.html.erb
<h1>Home of the Recipes!!</h1>
<!--
<p>Find me in app/views/page/home.html.erb</p>
<% 7.times do %>
<%= ("Ho! <br />").html_safe %>
<% end %>
-->

app/views/page/login.html.erb
<h1>
<%= link_to "Home", page_home_path %><br />
<%= page_home_url %>
</h1>

app/views/page/product.html.erb
<h1>Page#product</h1>
<p>Find me in app/views/page/product.html.erb</p>

app/views/page/recipes.html.erb
<h1>Page#recipes</h1>
<p>Find me in app/views/page/recipes.html.erb</p>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :html =>  {:multipart => true} ) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :made_by %><br />
    <%= f.text_field :made_by %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <!-- <%= f.text_area :ingredients %> -->
    <%= f.text_area :ingredients ,  :class => "tinymce", :rows => 30, :cols => 60 %>
  </div>
  <div class="field">
    <%= f.label :last_made %><br />
    <%= f.datetime_select :last_made %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :serves %><br />
    <%= f.number_field :serves %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= tinymce %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>
<%= will_paginate @recipes, :class => 'apple_pagination' %>
<table>
  <tr>
    <th>Name</th>
    <th>Made by</th>
    <th>Ingredients</th>
    <!-- <th>Last made</th> -->
    <th>Image</th>
    <th>Serves</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.name, recipe %></td>
    <td><%= recipe.made_by %></td>
    <td><%= truncate(recipe.ingredients).html_safe %></td>
    <!-- <td><%= recipe.last_made %></td> -->
    <td><%= link_to "My Image", "/assets/#{recipe.image}" %></td>
    <td><%= recipe.serves %></td>
    <td><%= number_to_currency recipe.cost %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <!--<td><%= link_to 'Email Recipe', email_recipe_path(recipe) %></td>-->
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @recipes, :class => 'apple_pagination' %>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Made by:</b>
  <%= @recipe.made_by %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <b>Last made:</b>
  <%= @recipe.last_made %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @recipe.image %>
</p>

<p>
  <b>Serves:</b>
  <%= @recipe.serves %>
</p>

<p>
  <b>Cost:</b>
  <%= number_to_currency @recipe.cost %>
</p>

<p>
  <b>Avatar:</b>
  <%= image_tag @recipe.avatar.url %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>


<% @recipe.reviews.each do |review| %>
<hr />
<b> <%= review.title%></b><%= link_to 'Remove', recipe_review_path(review.recipe, review), :confirm => 'Really Remove Comment?', :method => :delete %><br />
<%= time_ago_in_words(review.created_at) %> ago, <%= review.author%> said:<br />
<p> <%= review.content%></p>
<%= review.rating%>
<hr />
<% end %>
<br /><br /><br />
<hr /><h3>Give a REVIEW</h3><hr />

<%= form_for([@recipe, @recipe.reviews.build]) do |f| %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :recipe %><br />
    <%= f.text_field :recipe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Content</th>
    <th>Rating</th>
    <th>Recipe</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td><%= review.author %></td>
    <td><%= review.content %></td>
    <td><%= review.rating %></td>
    <td><%= review.recipe %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @review.title %>
</p>

<p>
  <b>Author:</b>
  <%= @review.author %>
</p>

<p>
  <b>Content:</b>
  <%= @review.content %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Recipe:</b>
  <%= @review.recipe %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/say/goodbye.html.erb
<h1>Bye Pawan</h1>
<img src="/assets/rails.png">

app/views/say/hello.html.erb
<h1>Hello Pawan</h1>
<img src="/assets/rails.png">

app/views/shared/_navigation.html.erb
<div class="menu">
	<ul>
		<li><%= link_to_unless_current "Home", page_home_path %></li>
		<!--<li><%= link_to_unless_current "About Us", page_about_us_path, :alt => 'About Us' %></a></li>-->
		<li><%= link_to_unless_current "Recipes", recipes_path %></li>
		<li><%= link_to_unless_current "Store", store_path %></li>
		<!--<li><%= link_to_unless_current "Calender", page_calender_path %></li>-->
		<!--<li><%= link_to_unless_current "Blog", page_blog_path %></li>-->
		<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
	</ul>
</div>


app/views/stores/index.html.erb
<h1>Listing recipes</h1>
<%= will_paginate @recipes, :class => 'apple_pagination' %>
<table>
  <tr>
    <th>Name</th>
    <th>Ingredients</th>
    <th>Image</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.name, store_id_path(recipe.id) %></td>
    <td><%= truncate(recipe.ingredients).html_safe %></td>
    <td><%= link_to "My Image", "/assets/#{recipe.image}" %></td>
    <% if user_signed_in? then %>
    <td><%= number_to_currency recipe.cost %></td>
    <% end %>
    <td><%= link_to 'Show', store_id_path(recipe.id) %></td>
    
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @recipes, :class => 'apple_pagination' %>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Made by:</b>
  <%= @recipe.made_by %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe.ingredients.html_safe %>
</p>

<p>
  <b>Last made:</b>
  <%= @recipe.last_made %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @recipe.image %>
</p>

<p>
  <b>Serves:</b>
  <%= @recipe.serves %>
</p>

<p>
  <b>Cost:</b>
  <%= number_to_currency @recipe.cost %>
</p>


<%= link_to 'Back', store_path %>